### ISSUE TITLE
Possible synchronization issue with deletions

### ISSUE THREAD

**Issue by raphaelm** [raphaelm/cockatiel#9]
Scenario:
- User uploads file to node A, does not get replicated to B because of network issues
- User sends DELETE command to B, B does not do anyting because it does not know the file
- Network issues are resolved, file is transferred from A to B and now present on every node, even though it should be deleted.

**Comment by raphaelm** [comment]
@funkybob I have yet to come up with a good idea for this, do you happen to have one?

**Comment by funkybob** [comment]
This is where systems using a shared state machine prove much more solid... since rejoining the group means catching up on the shared state log.
Do we treat actions from users different to actions from friends?  If so, actions from users can _always_ be parrotted, whilst actions from friends are not?

**Comment by raphaelm** [comment]
> Do we treat actions from users different to actions from friends? If so, actions from users can always be parrotted, whilst actions from friends are not?

Currently we treat them the same. But yes, that is the one idea I had in my mind so far. However, I feel that parrotting deletions of non-existant files might lead to other failure situations if we create and delete the same file multiple times. This could be solved by making file-names not only dependent on the content's hash but also on the timestamp.

I'll try to write regression tests for this if I get to it and then try to fix it that way.

**Comment by raphaelm** [comment]
I just ran into a race condition where if you PUT and DELETE a file in a failure scenario like above, you can end up with to servers ping-pong-ing the file forever or at least a long time without a well-defined outcome. I see only one option: Time-dependent filenames and a log of files that are known to be deleted, such that a deleted file can never appear again.

**Comment by raphaelm** [comment]
I implemented the suggestion of my last comment and so far, I could not deliberately break it ;)

**Comment by raphaelm** [comment]
Yes, I believe this is fixed due to the addition of a deletion log.
